### ISSUE TITLE
Network is not detected

### ISSUE THREAD

**Issue by Calinou** [mashlol/mintr#3]
[I've installed Mintr on my VPS](http://mt.nerdpol.ovh:3000/); the network is not detected, it keeps reporting 0 KB/s up and down. The network interface is called `venet0`. How do I go about specifying the network interface when starting?

Perhaps there should be automatic detection of the used interface.

**Comment by mashlol** [comment]
Ah, yes the network detection is very poor at the moment, will need to work on this.  Currently it selects the second network interface I think, since `lo` is usually first.

I think the ideal scenario here would be to have a dropdown to switch between which network interface is shown.

Or, alternatively, add all network interfaces except `lo` and report that.

**Comment by mashlol** [comment]
@Calinou please let me know if 0.0.8 fixes this.

**Comment by Calinou** [comment]
I get this at regular intervals when running as an unprivileged user:

```
{ [Error: Command failed: /bin/sh: 1: ifconfig: not found
] killed: false, code: 127, signal: null }
```

`ifconfig` is deprecated, please use `ip addr` instead, by the way. `ip addr` works as an unprivileged user.

Back on topic: 0.0.8 still shows zero network usage, even when running Mintr as root.

**Comment by mashlol** [comment]
@Calinou please let me know if 0.0.9 fixes this.  I'm now using `ip` instead of `ifconfig`, so we'll see if we get better results from this.

**Comment by mashlol** [comment]
Looks like this is working now on your VPS.
